In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head(2)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157

In [4]:
time.head(3)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00          Днепр.м 43 позн.с д/ж *.о  067.16.34.576

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
date.isnull().sum()

date          0
product_id    0
city_id       0
orders        0
dtype: int64

In [7]:
time.isnull().sum()

date    0
msg     0
dtype: int64

In [9]:
date['date']=pd.to_datetime(date['date'])

In [10]:
date.head(3)

        date  product_id  city_id  orders
0 2019-12-10        5628       25       3
1 2018-08-15        3646       14     157
2 2018-10-23        1859       25       1

In [11]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [12]:
time.head(3)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00          Днепр.м 43 позн.с д/ж *.о  067.16.34.576

In [13]:
time['date']= pd.to_datetime(time['date'])

In [14]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [15]:
date['date_year'] = date['date'].dt.year

In [16]:
date.head(3)

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018

In [17]:
date['date_month'] = date['date'].dt.month

In [18]:
date.head(3)

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10

In [19]:
date['date_day'] = date['date'].dt.day

In [20]:
date.head(2)

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15

In [21]:
date['date_month_name'] = date['date'].dt.month_name()

In [22]:
date.head(3)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August
2,2018-10-23,1859,25,1,2018,10,23,October

In [24]:
date['date_dow'] = date['date'].dt.dayofweek

In [25]:
date.head(3)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2
2,2018-10-23,1859,25,1,2018,10,23,October,1

In [26]:
date['date_dow_name'] = date['date'].dt.day_name()

In [27]:
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday

In [28]:
date['date_is_weekend']=np.where(date['date_dow_name'].isin(['Sunday','Saturday']), 1,0)

In [31]:
date.sample(3)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend
88,2019-10-11,925,25,10,2019,10,11,October,4,Friday,0
957,2019-07-12,5250,3,9,2019,7,12,July,4,Friday,0
177,2019-08-10,585,17,13,2019,8,10,August,5,Saturday,1

In [33]:
date['date_week'] = date['date'].dt.isocalendar().week

In [34]:
date.head(3)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,23,October,1,Tuesday,0,43

In [35]:
date.drop(columns=['product_id', 'city_id','orders'], inplace=True)

In [36]:
date.head(3)

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,10,December,1,Tuesday,0,50
1,2018-08-15,2018,8,15,August,2,Wednesday,0,33
2,2018-10-23,2018,10,23,October,1,Tuesday,0,43

In [38]:
date['quarter']=date['date'].dt.quarter

In [39]:
date.head(2)

,date,date_year,date_month,date_day,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,10,December,1,Tuesday,0,50,4
1,2018-08-15,2018,8,15,August,2,Wednesday,0,33,3

In [40]:
import datetime
today = datetime.datetime.today()

In [41]:
today

datetime.datetime(2024, 11, 11, 20, 6, 30, 597283)

In [42]:
today-date['date']

0     1798 days 20:06:30.597283
1     2280 days 20:06:30.597283
2     2211 days 20:06:30.597283
3     1913 days 20:06:30.597283
4     2136 days 20:06:30.597283
                 ...
995   2226 days 20:06:30.597283
996   2167 days 20:06:30.597283
997   2015 days 20:06:30.597283
998   2080 days 20:06:30.597283
999   1854 days 20:06:30.597283
Name: date, Length: 1000, dtype: timedelta64[ns]

In [44]:
(today-date['date']).dt.days

0      1798
1      2280
2      2211
3      1913
4      2136
       ...
995    2226
996    2167
997    2015
998    2080
999    1854
Name: date, Length: 1000, dtype: int64

In [46]:
time.head()

                 date                                                msg
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [47]:
time.drop(columns=['msg'],inplace=True)

In [48]:
time.head(3)

                 date
0 2013-12-15 00:50:00
1 2014-04-29 23:40:00
2 2012-12-30 00:21:00

In [49]:
time['hour']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second

In [50]:
time.head(2)

                 date  hour  min  sec
0 2013-12-15 00:50:00     0   50    0
1 2014-04-29 23:40:00    23   40    0

In [51]:
time['time']=time['date'].dt.time

In [52]:
time.head(3)

                 date  hour  min  sec      time
0 2013-12-15 00:50:00     0   50    0  00:50:00
1 2014-04-29 23:40:00    23   40    0  23:40:00
2 2012-12-30 00:21:00     0   21    0  00:21:00

In [53]:
today-time['date']

0     3984 days 19:16:30.597283
1     3848 days 20:26:30.597283
2     4334 days 19:45:30.597283
3     3636 days 19:35:30.597283
4     4033 days 20:55:30.597283
                 ...
995   4623 days 19:16:30.597283
996   3944 days 20:52:30.597283
997   4409 days 20:29:30.597283
998   4525 days 20:32:30.597283
999   3797 days 20:41:30.597283
Name: date, Length: 1000, dtype: timedelta64[ns]