In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv('customer.csv')

In [30]:
df.head(2)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No

In [31]:
df['education'].value_counts()

education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [32]:
df['gender'].value_counts()

gender
Female    29
Male      21
Name: count, dtype: int64

In [33]:
df['purchased'].value_counts()

purchased
No     26
Yes    24
Name: count, dtype: int64

In [34]:
df['review'].value_counts()

review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [35]:
df.shape

(50, 5)

In [36]:
df['age'].value_counts()

age
57    3
74    3
30    2
18    2
22    2
39    2
16    2
61    1
94    1
73    1
92    1
89    1
86    1
34    1
38    1
45    1
77    1
76    1
64    1
48    1
23    1
27    1
83    1
96    1
69    1
51    1
70    1
72    1
31    1
60    1
65    1
98    1
15    1
53    1
75    1
59    1
19    1
97    1
32    1
68    1
25    1
Name: count, dtype: int64

In [37]:
df.isnull().sum()

age          0
gender       0
review       0
education    0
purchased    0
dtype: int64

In [38]:
df.describe()

             age
count  50.000000
mean   54.160000
std    25.658161
min    15.000000
25%    30.250000
50%    57.000000
75%    74.000000
max    98.000000

In [39]:
df.sample(5)

    age  gender   review education purchased
5    31  Female  Average    School       Yes
49   25  Female     Good        UG        No
41   23    Male     Good        PG       Yes
28   48    Male     Poor    School        No
26   53  Female     Poor        PG        No

In [40]:
df = df.iloc[:, 2:]

In [41]:
df.sample(5)

     review education purchased
49     Good        UG        No
5   Average    School       Yes
44  Average        UG        No
10     Good        UG       Yes
31     Poor    School       Yes

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size = 0.2)

In [44]:
X_train

     review education
0   Average    School
45     Poor        PG
3      Good        PG
40     Good    School
14     Poor        PG
11     Good        UG
5   Average    School
12     Poor    School
38     Good    School
31     Poor    School
16     Poor        UG
6      Good    School
37  Average        PG
19     Poor        PG
9      Good        UG
17     Poor        UG
39     Poor        PG
20  Average    School
29  Average        UG
2      Good        PG
47     Good        PG
21  Average        PG
49     Good        UG
26     Poor        PG
48     Good        UG
25     Good    School
23     Good    School
15     Poor        UG
44  Average        UG
13  Average    School
32  Average        UG
28     Poor    School
41     Good        PG
22     Poor        PG
10     Good        UG
24  Average        PG
43     Poor        PG
46     Poor        PG
33     Good        PG
27     Poor        PG

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
oe = OrdinalEncoder(categories = [['Poor', 'Average', 'Good'], 
                                 ['School', 'UG', 'PG']])

In [47]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [48]:
X_train

     review education
0   Average    School
45     Poor        PG
3      Good        PG
40     Good    School
14     Poor        PG
11     Good        UG
5   Average    School
12     Poor    School
38     Good    School
31     Poor    School
16     Poor        UG
6      Good    School
37  Average        PG
19     Poor        PG
9      Good        UG
17     Poor        UG
39     Poor        PG
20  Average    School
29  Average        UG
2      Good        PG
47     Good        PG
21  Average        PG
49     Good        UG
26     Poor        PG
48     Good        UG
25     Good    School
23     Good    School
15     Poor        UG
44  Average        UG
13  Average    School
32  Average        UG
28     Poor    School
41     Good        PG
22     Poor        PG
10     Good        UG
24  Average        PG
43     Poor        PG
46     Poor        PG
33     Good        PG
27     Poor        PG

In [49]:
X_train1 = oe.transform(X_train)

In [50]:
X_train1

array([[1., 0.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.]])

In [51]:
X_train

     review education
0   Average    School
45     Poor        PG
3      Good        PG
40     Good    School
14     Poor        PG
11     Good        UG
5   Average    School
12     Poor    School
38     Good    School
31     Poor    School
16     Poor        UG
6      Good    School
37  Average        PG
19     Poor        PG
9      Good        UG
17     Poor        UG
39     Poor        PG
20  Average    School
29  Average        UG
2      Good        PG
47     Good        PG
21  Average        PG
49     Good        UG
26     Poor        PG
48     Good        UG
25     Good    School
23     Good    School
15     Poor        UG
44  Average        UG
13  Average    School
32  Average        UG
28     Poor    School
41     Good        PG
22     Poor        PG
10     Good        UG
24  Average        PG
43     Poor        PG
46     Poor        PG
33     Good        PG
27     Poor        PG

In [52]:
X_train1 = pd.DataFrame(X_train1, columns = X_train.columns)

In [53]:
X_train1

    review  education
0      1.0        0.0
1      0.0        2.0
2      2.0        2.0
3      2.0        0.0
4      0.0        2.0
5      2.0        1.0
6      1.0        0.0
7      0.0        0.0
8      2.0        0.0
9      0.0        0.0
10     0.0        1.0
11     2.0        0.0
12     1.0        2.0
13     0.0        2.0
14     2.0        1.0
15     0.0        1.0
16     0.0        2.0
17     1.0        0.0
18     1.0        1.0
19     2.0        2.0
20     2.0        2.0
21     1.0        2.0
22     2.0        1.0
23     0.0        2.0
24     2.0        1.0
25     2.0        0.0
26     2.0        0.0
27     0.0        1.0
28     1.0        1.0
29     1.0        0.0
30     1.0        1.0
31     0.0        0.0
32     2.0        2.0
33     0.0        2.0
34     2.0        1.0
35     1.0        2.0
36     0.0        2.0
37     0.0        2.0
38     2.0        2.0
39     0.0        2.0

In [54]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [55]:
from sklearn.preprocessing import LabelEncoder

In [56]:
le = LabelEncoder()

In [57]:
le.fit(y_train)

LabelEncoder()

In [58]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [59]:
 le.fit(y_train)

LabelEncoder()

In [60]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [61]:
y_train1 = le.transform(y_train)

In [63]:
y_train1

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0])