In [2]:
# Very intuitive 
# Dependent on data
# Easy when domain knowledge already exists

In [3]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','SibSp', 'Parch', 'Survived']]

In [5]:
df.head(3)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

Age         0
Pclass      0
SibSp       0
Parch       0
Survived    0
dtype: int64

In [10]:
df.head(3)

    Age  Pclass  SibSp  Parch  Survived
0  22.0       3      1      0         0
1  38.0       1      1      0         1
2  26.0       3      0      0         1

In [11]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [12]:
X

      Age  Pclass  SibSp  Parch
0    22.0       3      1      0
1    38.0       1      1      0
2    26.0       3      0      0
3    35.0       1      1      0
4    35.0       3      0      0
..    ...     ...    ...    ...
885  39.0       3      0      5
886  27.0       2      0      0
887  19.0       1      0      0
889  26.0       1      0      0
890  32.0       3      0      0

[714 rows x 4 columns]

In [13]:
y

0      0
1      1
2      1
3      1
4      0
      ..
885    0
886    0
887    1
889    1
890    0
Name: Survived, Length: 714, dtype: int64

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
lor = LogisticRegression()

In [16]:
from sklearn.model_selection import train_test_split as tts

In [17]:
X_train,X_test,y_train,y_test=tts(X,y,test_size=0.2,random_state=42)

In [18]:
lor.fit(X_train,y_train)

LogisticRegression()

In [19]:
y_pred = lor.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
accuracy_score(y_pred,y_test)

0.6923076923076923

In [22]:
from sklearn.model_selection import cross_val_score

In [23]:
np.mean(cross_val_score(lor,X,y,scoring='accuracy', cv=10))

0.6921165884194054

In [24]:
X_train.head(3)

      Age  Pclass  SibSp  Parch
328  31.0       3      1      1
73   26.0       3      1      0
253  30.0       3      1      0

In [25]:
X_train['family_size'] = X_train['SibSp']+X_train['Parch']

In [27]:
X_train.drop(columns=['Parch', 'SibSp'], inplace=True)

In [28]:
X_train.head(3)

      Age  Pclass  family_size
328  31.0       3            2
73   26.0       3            1
253  30.0       3            1

In [29]:
X_test['family_size'] = X_test['SibSp']+X_test['Parch']

In [30]:
X_test.drop(columns=['Parch', 'SibSp'], inplace=True)

In [31]:
lor2=LogisticRegression()

In [32]:
lor2.fit(X_train,y_train)

LogisticRegression()

In [33]:
y_pred2 = lor2.predict(X_test)

In [34]:
accuracy_score(y_pred2,y_test)

0.6783216783216783

In [35]:
np.mean(cross_val_score(lor2,X_train,y_train,scoring='accuracy', cv=10))

0.696854204476709

In [38]:
X_train.head(3)

      Age  Pclass  family_size
328  31.0       3            2
73   26.0       3            1
253  30.0       3            1

In [39]:
X_train['family_size']+=1

In [40]:
X_train.head(2)

      Age  Pclass  family_size
328  31.0       3            3
73   26.0       3            2

In [41]:
X_test['family_size']+=1

In [42]:
lor3 = LogisticRegression()

In [43]:
lor3.fit(X_train,y_train)

LogisticRegression()

In [44]:
y_pred3 = lor3.predict(X_test)

In [45]:
accuracy_score(y_pred3,y_test)

0.6783216783216783

In [46]:
np.mean(cross_val_score(lor3,X_train,y_train,scoring='accuracy', cv=10))

0.696854204476709