In [40]:
import numpy as np
import pandas as pd

np.random.seed(23) 

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20)

df = pd.DataFrame(class1_sample, columns=['feature1', 'feature2', 'feature3'])
df['target'] = 1

mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20)

df1 = pd.DataFrame(class2_sample, columns=['feature1', 'feature2', 'feature3'])
df1['target'] = 0

# Using pd.concat instead of append
df = pd.concat([df, df1], ignore_index=True)

# Shuffle rows
df = df.sample(frac=1).reset_index(drop=True)

In [41]:
df.shape

(40, 4)

In [42]:
df.head(3)

   feature1  feature2  feature3  target
0 -0.367548 -1.137460 -1.322148       1
1  0.177061 -0.598109  1.226512       0
2  0.420623  0.411620 -0.071324       1

In [43]:
df['target'].value_counts()

target
1    20
0    20
Name: count, dtype: int64

In [44]:
import plotly.express as px
fig = px.scatter_3d(df, x=df['feature1'], y=df['feature2'], z=df['feature3'],
                   color=df['target'].astype('str'))
fig.update_traces(marker=dict(size=12, line=dict(width=12, color='DarkSlateGrey')),
                 selector=dict(mode='markers'))

C:\Users\dell\anaconda3\Lib\site-packages\plotly\express\_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

In [47]:
df.iloc[:, 0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [48]:
df.head(3)

   feature1  feature2  feature3  target
0 -0.700809 -1.525586 -1.749156       1
1 -0.224481 -1.010757  0.491251       0
2 -0.011456 -0.046935 -0.649616       1

In [49]:
df.head(3)

   feature1  feature2  feature3  target
0 -0.700809 -1.525586 -1.749156       1
1 -0.224481 -1.010757  0.491251       0
2 -0.011456 -0.046935 -0.649616       1

In [50]:
covarience_matrix = np.cov([df.iloc[:,0], df.iloc[:,1], df.iloc[:,2]])
print('Covariance Matrix : \n', covarience_matrix)

Covariance Matrix :
 [[1.02564103 0.20478114 0.080118  ]
 [0.20478114 1.02564103 0.19838882]
 [0.080118   0.19838882 1.02564103]]

In [51]:
eigen_values, eigen_vectors = np.linalg.eig(covarience_matrix)

In [52]:
eigen_values

array([1.3536065 , 0.94557084, 0.77774573])

In [53]:
eigen_vectors

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442],
       [-0.52848211,  0.72025103,  0.44938304]])

In [54]:
pc = eigen_vectors[0:2]
pc

array([[-0.53875915, -0.69363291,  0.47813384],
       [-0.65608325, -0.01057596, -0.75461442]])

In [57]:
df.head(3)

   feature1  feature2  feature3  target
0 -0.700809 -1.525586 -1.749156       1
1 -0.224481 -1.010757  0.491251       0
2 -0.011456 -0.046935 -0.649616       1

In [58]:
transformed_df = np.dot(df.iloc[:,0:3], pc.T)

In [61]:
transformed_df[0:5]

array([[ 0.59943321,  1.79586208],
       [ 1.05691919, -0.2127375 ],
       [-0.27187555,  0.49822203],
       [-0.62158585,  0.02311035],
       [ 1.56728555,  1.73096695]])

In [68]:
new_df = pd.DataFrame(transformed_df, columns=['PC1', 'PC2'])

In [69]:
new_df.head(2)

        PC1       PC2
0  0.599433  1.795862
1  1.056919 -0.212737

In [70]:
new_df['target'] = df['target'].values

In [71]:
new_df.head(2)

        PC1       PC2  target
0  0.599433  1.795862       1
1  1.056919 -0.212737       0

In [72]:
new_df['target'] = new_df['target'].astype('str')
fig = px.scatter(x=new_df['PC1'],
                 y=new_df['PC2'],
                 color=new_df['target'],
                 color_discrete_sequence=px.colors.qualitative.G10
                )

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                                        color='DarkSlateGrey')),
                  selector=dict(mode='markers'))
fig.show()

C:\Users\dell\anaconda3\Lib\site-packages\plotly\express\_core.py:1979: FutureWarning:

When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.