# Series Practice

In [1]:
import pandas as pd
import numpy as np

In [2]:
country=['India', 'Pakistan', 'Usa', 'Nepal', 'Sri Lanka']
pd.Series(country)

0        India
1     Pakistan
2          Usa
3        Nepal
4    Sri Lanka
dtype: object

In [3]:
runs=[12,34,5,34,3,4]
pd.Series(runs)

0    12
1    34
2     5
3    34
4     3
5     4
dtype: int64

In [4]:
marks=[67,56,32,56,74,63]
sub=['English', 'Maths', 'Hindi', 'Science', 'Social', 'EPh']
pd.Series(marks,index=sub)

English    67
Maths      56
Hindi      32
Science    56
Social     74
EPh        63
dtype: int64

In [5]:
marks=[12,34,24,52,55,56]
sub=['maths','EPH', 'Opt Maths', 'Social', 'Science','Nepali']
pd.Series(marks, index=sub, name='Subhanjal Marks')

maths        12
EPH          34
Opt Maths    24
Social       52
Science      55
Nepali       56
Name: Subhanjal Marks, dtype: int64

In [6]:
marks={
    'Maths':45,
    'Science':54,
    'Eph':34,
    'English':56,
}
marks_series=pd.Series(marks,name='Subhanjal Marks')

In [7]:
marks_series

Maths      45
Science    54
Eph        34
English    56
Name: Subhanjal Marks, dtype: int64

In [8]:
marks_series.size

4

In [9]:
marks_series.dtype

dtype('int64')

In [10]:
marks_series.name

'Subhanjal Marks'

In [11]:
marks_series.is_unique

True

In [12]:
marks_series.index

Index(['Maths', 'Science', 'Eph', 'English'], dtype='object')

In [13]:
marks_series.values

array([45, 54, 34, 56], dtype=int64)

In [14]:
data=pd.read_csv('subs.csv')

In [15]:
data.head(3)

   Subscribers gained
0                  48
1                  57
2                  40

In [16]:
type(data)

pandas.core.frame.DataFrame

In [17]:
data_in_series=data.squeeze('columns')

In [18]:
data_in_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [19]:
data.size

365

In [20]:
data.sum()

Subscribers gained    49510
dtype: int64

In [21]:
data2=pd.read_csv('kohli_ipl.csv').squeeze('columns')

In [22]:
type(data2)

pandas.core.frame.DataFrame

In [23]:
data2

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [24]:
data2.sum()

match_no    23220
runs         6634
dtype: int64

In [25]:
data3=pd.read_csv('bollywood.csv', index_col='movie')

In [26]:
type(data3)

pandas.core.frame.DataFrame

In [27]:
data3.head()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar

In [28]:
data3=data3.squeeze()

In [29]:
type(data3)

pandas.core.series.Series

In [30]:
data3.head()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
Name: lead, dtype: object

In [31]:
data3.size

1500

In [32]:
data3.shape

(1500,)

In [33]:
data3.sample(3)

movie
Zila Ghaziabad         Vivek Oberoi
Evening Shadows    Mona Ambegaonkar
Badmashiyaan          Sidhant Gupta
Name: lead, dtype: object

In [34]:
data3.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [35]:
data3.value_counts().sort_values()

Chiranjeevi            1
Saurav Chakraborty     1
Shashank Udapurkar     1
Urvashi Rautela        1
Anuj Sachdeva          1
                      ..
Sanjay Dutt           26
Salman Khan           31
Ajay Devgn            38
Amitabh Bachchan      45
Akshay Kumar          48
Name: lead, Length: 566, dtype: int64

In [36]:
data3.value_counts().sort_values(ascending=False)

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Dwij Yadav           1
Samir Aftab          1
Sherlyn Chopra       1
Kavin Dave           1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [37]:
data2.head(3)

   match_no  runs
0         1     1
1         2    23
2         3    13

In [38]:
data2_new=data2.drop(columns='match_no')

In [39]:
data2_new.head(2)

   runs
0     1
1    23

In [40]:
data2.sort_values(by='runs', ascending=False)

     match_no  runs
127       128   113
125       126   109
122       123   108
163       164   100
119       120   100
..        ...   ...
92         93     0
210       211     0
129       130     0
7           8     0
134       135     0

[215 rows x 2 columns]

In [41]:
data2.head(3)

   match_no  runs
0         1     1
1         2    23
2         3    13