In [1]:
import pandas as pd
import numpy as np

In [2]:
country = ['India', 'Pakistan', 'USA', 'Nepal', 'Sri Lanka']
pd.Series(country)

0        India
1     Pakistan
2          USA
3        Nepal
4    Sri Lanka
dtype: object

In [3]:
runs= [12,34,654,745,745]
pd.Series(runs)

0     12
1     34
2    654
3    745
4    745
dtype: int64

In [4]:
marks =[67, 56,334,64,342,324]
sub=['English', 'Maths', 'Hindi', 'Science', 'Social','EPH']
pd.Series(marks, index=sub)

English     67
Maths       56
Hindi      334
Science     64
Social     342
EPH        324
dtype: int64

In [5]:
pd.Series(marks, index=sub, name='Nitesh ke marks')

English     67
Maths       56
Hindi      334
Science     64
Social     342
EPH        324
Name: Nitesh ke marks, dtype: int64

In [6]:
marks = pd.Series(marks, index=sub, name='Nitesh ke marks')

In [9]:
marks = {
    'Maths': 56,
    'Science': 34,
    'English' : 55,
    'EPH': 66,
}
marks_series= pd.Series(marks,name='Nitish')
marks_series

Maths      56
Science    34
English    55
EPH        66
Name: Nitish, dtype: int64

In [10]:
marks_series.size

4

In [11]:
marks_series.dtype

dtype('int64')

In [12]:
marks_series.name

'Nitish'

In [14]:
marks_series.is_unique

True

In [15]:
#is unique le items in the series repeat vaxa ki nai herxa
pd.Series([1,2,3,4,5,5,6]).is_unique

False

In [18]:
marks_series.index

Index(['Maths', 'Science', 'English', 'EPH'], dtype='object')

In [19]:
marks_series.values

array([56, 34, 55, 66], dtype=int64)

In [22]:
data = pd.read_csv('subs.csv')
data.head()

   Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [23]:
#Here the data is a dataframe, when we use read_csv it is read as
#dataframe by default
type(data)

pandas.core.frame.DataFrame

In [24]:
#however we can convert it to series
data = pd.read_csv('subs.csv', squeeze=True)
data.head()

C:\Users\dell\AppData\Local\Temp\ipykernel_6088\1665290855.py:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  data = pd.read_csv('subs.csv', squeeze=True)

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [28]:
#data = pd.read_csv('subs.csv').squeeze("columns")
# yesari use garney vaneko ho
data = pd.read_csv('subs.csv').squeeze("columns")
type(data)

pandas.core.series.Series

In [29]:
data.size

365

In [30]:
data.sum()

49510

In [33]:
data2 = pd.read_csv('kohli_ipl.csv').squeeze('columns')
type(data2)

pandas.core.frame.DataFrame

In [34]:
data2

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [35]:
data2.sum()

match_no    23220
runs         6634
dtype: int64

In [39]:
data3=pd.read_csv('bollywood.csv', index_col='movie')
type(data3)
data3

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [43]:
data3=data3.squeeze()
type(data3)

pandas.core.series.Series

In [47]:
#sample shows ddata randomly
data3.sample(5)

movie
Running Shaadi                          Arsh Bajwa
Roar: Tigers of the Sundarbans        Aadil Chahal
Banjo (2016 film)                 Riteish Deshmukh
Wafa: A Deadly Love Story            Rajesh Khanna
Sheesha (2005 film)                    Neha Dhupia
Name: lead, dtype: object

In [48]:
#value_counts-->item ko frequency vanxa
data3.value_counts()

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Diganth              1
Parveen Kaur         1
Seema Azmi           1
Akanksha Puri        1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [49]:
#sort_values-->
data3.value_counts().sort_values()

Chiranjeevi            1
Saurav Chakraborty     1
Shashank Udapurkar     1
Urvashi Rautela        1
Anuj Sachdeva          1
                      ..
Sanjay Dutt           26
Salman Khan           31
Ajay Devgn            38
Amitabh Bachchan      45
Akshay Kumar          48
Name: lead, Length: 566, dtype: int64

In [50]:
#high to low garna paryo vane
data3.value_counts().sort_values(ascending=False)

Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Dwij Yadav           1
Samir Aftab          1
Sherlyn Chopra       1
Kavin Dave           1
Edwin Fernandes      1
Name: lead, Length: 566, dtype: int64

In [52]:
data2

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [53]:
data2_new=data2.drop(columns='match_no')
data2_new.head()

   runs
0     1
1    23
2    13
3    12
4     1

In [59]:
data2.sort_values(by='runs', ascending=False)

     match_no  runs
127       128   113
125       126   109
122       123   108
163       164   100
119       120   100
..        ...   ...
92         93     0
210       211     0
129       130     0
7           8     0
134       135     0

[215 rows x 2 columns]

In [61]:
data2.sort_values(by='runs', ascending=False).head(1).values

array([[128, 113]], dtype=int64)

In [62]:
data2.sort_values(by='runs', ascending=False).head(1).values[0]

array([128, 113], dtype=int64)

In [64]:
#sort_values le main data ma changes lyaudaina it is temporary change
#However, permanent change lyauna inplace use garna pauxa

In [70]:
#sort_index--> alphabetically arrange garxa
data3.sort_index()

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: object

In [74]:
#SERIES MATHS METHODS
#count--> size le pani same kam garxa but there is a difference
#size le missing values lai pani count garxa but count le missing 
#values lai count gardaina
data2.count()

match_no    215
runs        215
dtype: int64

In [75]:
#sum and product
data.sum()

49510

In [76]:
data.product()

0

In [77]:
#mean median mode std var
data.mean()

135.64383561643837

In [78]:
data2.median()

match_no    108.0
runs         24.0
dtype: float64

In [81]:
print(data3.mode())
#Akshay Kumar is the most frequent item

0    Akshay Kumar
Name: lead, dtype: object

In [84]:
print(data.std()) #standard deviation nikalxa

62.67502303725269

In [85]:
print(data2.var())

match_no    3870.000000
runs         688.002478
dtype: float64

In [86]:
data.min()

33

In [87]:
data.max()

396

In [89]:
#describe--> sabai calculate garera dido raixa
data2.describe()

         match_no        runs
count  215.000000  215.000000
mean   108.000000   30.855814
std     62.209324   26.229801
min      1.000000    0.000000
25%     54.500000    9.000000
50%    108.000000   24.000000
75%    161.500000   48.000000
max    215.000000  113.000000

In [90]:
data.describe()

count    365.000000
mean     135.643836
std       62.675023
min       33.000000
25%       88.000000
50%      123.000000
75%      177.000000
max      396.000000
Name: Subscribers gained, dtype: float64

In [91]:
#SERIES INDEXING
x = pd.Series([12,13,14,15,45,64,74,33,64,64])
x[0]

12

In [95]:
#Negative indexing series ma kam gardaina
#String ma chai kam gardo raixa hai pheri

In [96]:
#SLICING
data[5:16]

5     46
6     33
7     40
8     44
9     74
10    49
11    56
12    49
13    42
14    39
15    44
Name: Subscribers gained, dtype: int64

In [97]:
data[-5:]

360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [98]:
data3[-5:]

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: object

In [103]:
data[[1,5,7,9]]

1    57
5    46
7    40
9    74
Name: Subscribers gained, dtype: int64

In [105]:
#using indexing
marks_series

Maths      56
Science    34
English    55
EPH        66
Name: Nitish, dtype: int64

In [106]:
marks_series[1]=100

In [107]:
marks_series

Maths       56
Science    100
English     55
EPH         66
Name: Nitish, dtype: int64

In [108]:
marks_series['Social Studies']=99
#it will not throw an error but add social studies to the Series
marks_series

Maths              56
Science           100
English            55
EPH                66
Social Studies     99
Name: Nitish, dtype: int64

In [109]:
#read garney bela chai error throw garxa hai

In [112]:
marks_series[2:4]=[100,100]
marks_series
#Fancy indexing ni use garna milyo

Maths              56
Science           100
English           100
EPH               100
Social Studies     99
Name: Nitish, dtype: int64

In [ ]:
#COPY AND VIEWS--> not very important though